apiVersion: v1
kind: Service              # 1
metadata:
  name: react
spec: 
  type: LoadBalancer       # Updated to expose the service externally
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: react             # Updated to match the app label in the Deployment
