apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where the resources will be deployed
namespace: default

# Prefix and suffix for resource names
namePrefix: myapp-
nameSuffix: -prod

# Resources to include in the kustomization
resources:
  - java_deployment.yaml
  - java_hpa.yaml
  - java_ingress.yaml
  - java_pvc.yaml
  - java_service.yaml
