apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puthon-fast
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
