apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - ingress.yaml
  - pv.yaml
  - service.yaml
  - serviceAccount.yaml
  - pvc.yaml

# Common Labels
commonLabels:
  app: jenkins
  
# Name Prefix
namePrefix: jenkins-

# Name Suffix
nameSuffix: -prod
