apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where the resources will be deployed
namespace: default              # Sets the namespace to 'prod'

# Prefix and suffix for resource names
namePrefix: myapp-              # Add a prefix to the resource names
nameSuffix: -prod               # Add a suffix to the resource names

# Resources to include in the kustomization
resources:
  - react_deployment.yaml
  - react_hpa.yaml
  - react_ingress.yaml
  - react_pvc.yaml
  - react_service.yaml

