apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: react-fast   # Updated to match the PVC name in the Deployment
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
