apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: react.example.com                             # 1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-service                         # 2
            port:
              number: 80
  ingressClassName: nginx                               # 3
