apiVersion: v1
kind: PersistentVolume
metadata:
  name: react-fast-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: standard
  hostPath: 
    path: /mnt/data/react-fast
