apiVersion: v1
kind: Service              # 1
metadata:
  name: react-service      # Updated to match the name used in Ingress
spec:
  type: LoadBalancer       # Exposes the service externally
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: react             # Matches the app label in the Deployment

