apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-react-fast-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/disks/data
