apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: yourdomain.com # Replace with your domain or leave empty for default
    http:
      paths:
      - path: /java
        pathType: Prefix
        backend:
          service:
            name: java-service # Replace with the name of your Java service
            port:
              number: 8080
      - path: /python
        pathType: Prefix
        backend:
          service:
            name: python-service # Replace with the name of your Python service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-service # This should match the actual name of your React service
            port:
              number: 80
