apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-react-fast-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
